name: health-check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # add manually button

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: jtalk/url-health-check-action@v2
        with:
          url: https://oj.pascal-lab.net/api/site/getCopyright
          max-attempts: 5
          retry-delay: 15s

      - uses: jtalk/url-health-check-action@v2
        with:
          url: https://tai-e.pascal-lab.net/
          max-attempts: 5
          retry-delay: 15s
